//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innov_Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "please Enter a Name")]
        //[RegularExpression(@"[a-zA-Z]", ErrorMessage = "Please Enter a Correct Name")]
        //[StringLength(20, MinimumLength = 2, ErrorMessage = "length must between 2 to 20 ")]
        //[Display(Name = "Customer Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Email Address")]
        //[Display(Name = "Email")]
        //[RegularExpression(@"[a-zA-Z0-9]+@[A-Za-z]+.[a-zA-Z]{2,4}", ErrorMessage = "Please Enter Correct Email Address")]
        //[EmailAddress]
        public string Email { get; set; }


        [Required(ErrorMessage = "please Enter a address")]
        //[RegularExpression(@"[a-zA-Z]", ErrorMessage = "Please Enter a Correct address")]
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
